enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.17.1.cjs

# reference: https://yarnpkg.com/features/security#age-gate
# background:
# https://jfrog.com/help/r/artifactory-recently-published-npm-packages-may-be-blocked-for-24-hours-new-client-enforcements/artifactory-recently-published-npm-packages-may-be-blocked-for-24-hours-new-client-enforcements
#
# fixes: ...are quarantined
#
#Running override package installation command:
#➤ YN0000: · Yarn 4.16.0
#➤ YN0000: ┌ Resolution step
#➤ YN0016: │ @storybook/addon-a11y@npm:10.4.6: All versions satisfying "10.4.6" are quarantined
#➤ YN0000: └ Completed in 1s 604ms
#➤ YN0000: · Failed with errors in 1s 618ms
npmMinimalAgeGate: 0
