import js from '@eslint/js';
import ts, { Config } from 'typescript-eslint';
import prettierConfigRecommended from 'eslint-plugin-prettier/recommended';
import storybookPlugin from 'eslint-plugin-storybook';
import reactPlugin from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import nextPlugin from '@next/eslint-plugin-next';
import graphqlPlugin from '@graphql-eslint/eslint-plugin';

import globals from 'globals';

import { fixupPluginRules } from '@eslint/compat';

export default [
    {
        files: ['** / *.{js,jsx,ts,tsx}'],
        processor: graphqlPlugin.processor,
        rules: {
            ...js.configs.recommended.rules,
        },
    },
    ...ts.configs.recommended,
    ...storybookPlugin.configs['flat/csf-strict'],
    {
        // also work on typescript files with extensions tsx
        files: ['**/*.{js,jsx,ts,tsx}'],
        processor: graphqlPlugin.processor,
    },
    {
        files: ['pages/api/**/*'],
        languageOptions: {
            globals: globals.node,
        },
    },
    {
        languageOptions: {
            globals: globals.browser,
        },
    },
    {
        plugins: {
            '@next/next': fixupPluginRules(nextPlugin),
        },
        rules: {
            ...nextPlugin.configs.recommended.rules,
            ...nextPlugin.configs['core-web-vitals'].rules,
        },
    },
    {
        // TEMP: until all sources got fixed
        rules: { '@typescript-eslint/no-explicit-any': 'off' },
    },
    {
        // TEMP: until sources got changed
        rules: {
            // e.g.  If you want a type meaning "any value", you probably want `unknown` instead
            //    '@typescript-eslint/ban-ts-comment': 'off',
            //'@typescript-eslint/no-empty-object-type': 'off',
            //'@typescript-eslint/no-wrapper-object-types': 'warn',
            //'@typescript-eslint/no-unused-vars': 'off',
        },
    },
    prettierConfigRecommended,
    {
        // TEMP: Some outdated, not properly formatted sources exist
        rules: {
            'prettier/prettier': 1,
        },
    },
    {
        files: ['**/*.{jsx,tsx}'],
        plugins: {
            react: fixupPluginRules(reactPlugin),
        },
        settings: { react: { version: 'detect' } },
        rules: {
            ...reactPlugin.configs.recommended.rules,
            // TEMP: code needs adoptions:
            'react/react-in-jsx-scope': 0,
            'react/prop-types': 0,
        },
    },
    {
        // TEMP code will need adoptions:
        rules: {
            'import/no-anonymous-default-export': 'off',
            'no-undef': 1,
            'no-console': 0,
        },
    },
    {
        plugins: { 'react-hooks': fixupPluginRules(reactHooks) },
        rules: {
            'react-hooks/rules-of-hooks': 'error',
            'react-hooks/exhaustive-deps': 'error',
        },
    },
    {
        ignores: [
            '**/node_modules',
            '**/coverage',
            '**/public',
            '**/build',
            '!**/.storybook',
            '**/storybook-static/',
            //'components/ui/',
            // generated by relay tools:
            'relay/__generated__/',
            './app/relay/[userName]/[repoName]/__generated__',
            './app/relay/[userName]/__generated__',
            './container/__generated__',
            './components/__generated__',
            // generated by graphql schema generator:
            'lib/types/resolvers.d.ts',
            'cypress',
            '**/eval-reg-suit/',
            '**/stuff/',
            '**/out_publish',
            '.next/**',
            '.yarn',
        ],
    },
] satisfies Config;
