/* eslint-disable */
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
/** Autogenerated input type of MergePullRequest */
export type MergePullRequestInput = {
    /** The email address to associate with this merge. */
    authorEmail?: string | null | undefined;
    /** A unique identifier for the client performing the mutation. */
    clientMutationId?: string | null | undefined;
    /** Commit body to use for the merge commit; if omitted, a default message will be used */
    commitBody?: string | null | undefined;
    /** Commit headline to use for the merge commit; if omitted, a default message will be used. */
    commitHeadline?: string | null | undefined;
    /** OID that the pull request head ref must match to allow merge; if omitted, no check is performed. */
    expectedHeadOid?: unknown;
    /** The merge method to use. If omitted, defaults to 'MERGE' */
    mergeMethod?: PullRequestMergeMethod | null | undefined;
    /** ID of the pull request to be merged. */
    pullRequestId: string | number;
};

/** Detailed status information about a pull request merge. */
export type MergeStateStatus =
    /** The head ref is out of date. */
    | 'BEHIND'
    /** The merge is blocked. */
    | 'BLOCKED'
    /** Mergeable and passing commit status. */
    | 'CLEAN'
    /** The merge commit cannot be cleanly created. */
    | 'DIRTY'
    /** The merge is blocked due to the pull request being a draft. */
    | 'DRAFT'
    /** Mergeable with passing commit status and pre-receive hooks. */
    | 'HAS_HOOKS'
    /** The state cannot currently be determined. */
    | 'UNKNOWN'
    /** Mergeable with non-passing commit status. */
    | 'UNSTABLE';

/** Whether or not a PullRequest can be merged. */
export type MergeableState =
    /** The pull request cannot be merged due to merge conflicts. */
    | 'CONFLICTING'
    /** The pull request can be merged. */
    | 'MERGEABLE'
    /** The mergeability of the pull request is still being calculated. */
    | 'UNKNOWN';

/** Represents available types of methods to use when merging a pull request. */
export type PullRequestMergeMethod =
    /** Add all commits from the head branch to the base branch with a merge commit. */
    | 'MERGE'
    /** Add all commits from the head branch onto the base branch individually. */
    | 'REBASE'
    /** Combine all commits from the head branch into a single commit in the base branch. */
    | 'SQUASH';

/** The possible states of a pull request. */
export type PullRequestState =
    /** A pull request that has been closed without being merged. */
    | 'CLOSED'
    /** A pull request that has been closed by being merged. */
    | 'MERGED'
    /** A pull request that is still open. */
    | 'OPEN';

/** The possible commit status states. */
export type StatusState =
    /** Status is errored. */
    | 'ERROR'
    /** Status is expected. */
    | 'EXPECTED'
    /** Status is failing. */
    | 'FAILURE'
    /** Status is pending. */
    | 'PENDING'
    /** Status is successful. */
    | 'SUCCESS';

export type CommitWithStatuses_CommitFragment = {
    __typename: 'Commit';
    authoredDate: unknown;
    commitUrl: unknown;
    message: string;
    status: {
        __typename: 'Status';
        id: string;
        state: StatusState;
        commit: { __typename: 'Commit'; oid: unknown } | null;
        contexts: Array<{
            __typename: 'StatusContext';
            avatarUrl: unknown;
            context: string;
            state: StatusState;
            description: string | null;
            targetUrl: unknown;
        }>;
    } | null;
} & { ' $fragmentName'?: 'CommitWithStatuses_CommitFragment' };

export type BranchInfoRowFragment_RefFragment = {
    __typename: 'Ref';
    name: string;
    id: string;
    target:
        | { __typename: 'Blob' }
        | ({ __typename: 'Commit' } & {
              ' $fragmentRefs'?: { CommitWithStatuses_CommitFragment: CommitWithStatuses_CommitFragment };
          })
        | { __typename: 'Tag' }
        | { __typename: 'Tree' }
        | null;
    associatedPullRequests: {
        __typename: 'PullRequestConnection';
        edges: Array<{
            __typename: 'PullRequestEdge';
            node:
                | ({ __typename: 'PullRequest'; id: string } & {
                      ' $fragmentRefs'?: { PullRequestMergeFragment_RefFragment: PullRequestMergeFragment_RefFragment };
                  })
                | null;
        } | null> | null;
    };
} & { ' $fragmentName'?: 'BranchInfoRowFragment_RefFragment' };

export type PullRequestMergeFragment_RefFragment = {
    __typename: 'PullRequest';
    id: string;
    headRefOid: unknown;
    number: number;
    url: unknown;
    title: string;
    mergeStateStatus: MergeStateStatus;
    closed: boolean;
    isDraft: boolean;
    merged: boolean;
    mergeable: MergeableState;
} & { ' $fragmentName'?: 'PullRequestMergeFragment_RefFragment' };

export type GetRepositoriesQueryVariables = Exact<{
    login: string;
    after?: string | null | undefined;
    first: number;
}>;

export type GetRepositoriesQuery = {
    repositoryOwner:
        | {
              __typename: 'Organization';
              login: string;
              id: string;
              repositories: {
                  __typename: 'RepositoryConnection';
                  totalCount: number;
                  pageInfo: { __typename: 'PageInfo'; hasNextPage: boolean; endCursor: string | null };
                  edges: Array<{
                      __typename: 'RepositoryEdge';
                      node: {
                          __typename: 'Repository';
                          id: string;
                          name: string;
                          nameWithOwner: string;
                          isFork: boolean;
                          url: unknown;
                          description: string | null;
                          pullRequests: { __typename: 'PullRequestConnection'; totalCount: number };
                      } | null;
                  } | null> | null;
              };
          }
        | {
              __typename: 'User';
              login: string;
              id: string;
              repositories: {
                  __typename: 'RepositoryConnection';
                  totalCount: number;
                  pageInfo: { __typename: 'PageInfo'; hasNextPage: boolean; endCursor: string | null };
                  edges: Array<{
                      __typename: 'RepositoryEdge';
                      node: {
                          __typename: 'Repository';
                          id: string;
                          name: string;
                          nameWithOwner: string;
                          isFork: boolean;
                          url: unknown;
                          description: string | null;
                          pullRequests: { __typename: 'PullRequestConnection'; totalCount: number };
                      } | null;
                  } | null> | null;
              };
          }
        | null;
};

export type UserFragmentStoryQueryQueryVariables = Exact<{ [key: string]: never }>;

export type UserFragmentStoryQueryQuery = {
    repositoryOwner:
        | ({ __typename: 'Organization' } & {
              ' $fragmentRefs'?: {
                  UserFragment_RepositoryOwner_Organization_Fragment: UserFragment_RepositoryOwner_Organization_Fragment;
              };
          })
        | ({ __typename: 'User' } & {
              ' $fragmentRefs'?: {
                  UserFragment_RepositoryOwner_User_Fragment: UserFragment_RepositoryOwner_User_Fragment;
              };
          })
        | null;
};

type UserFragment_RepositoryOwner_Organization_Fragment = {
    __typename: 'Organization';
    id: string;
    login: string;
    avatarUrl: unknown;
} & { ' $fragmentName'?: 'UserFragment_RepositoryOwner_Organization_Fragment' };

type UserFragment_RepositoryOwner_User_Fragment = {
    __typename: 'User';
    id: string;
    login: string;
    company: string | null;
    avatarUrl: unknown;
} & { ' $fragmentName'?: 'UserFragment_RepositoryOwner_User_Fragment' };

export type UserFragment_RepositoryOwnerFragment =
    | UserFragment_RepositoryOwner_Organization_Fragment
    | UserFragment_RepositoryOwner_User_Fragment;

export type UseMergePrMutationMutationVariables = Exact<{
    input: MergePullRequestInput;
}>;

export type UseMergePrMutationMutation = {
    mergePullRequest: {
        __typename: 'MergePullRequestPayload';
        pullRequest: {
            __typename: 'PullRequest';
            merged: boolean;
            state: PullRequestState;
            mergeStateStatus: MergeStateStatus;
        } | null;
    } | null;
};

export type GetUserWithReposQueryVariables = Exact<{
    userName: string;
}>;

export type GetUserWithReposQuery = {
    repositoryOwner:
        | ({ __typename: 'Organization'; id: string; login: string } & {
              ' $fragmentRefs'?: {
                  UserWithReposFragment_RepositoryOwner_Organization_Fragment: UserWithReposFragment_RepositoryOwner_Organization_Fragment;
              };
          })
        | ({ __typename: 'User'; id: string; login: string } & {
              ' $fragmentRefs'?: {
                  UserWithReposFragment_RepositoryOwner_User_Fragment: UserWithReposFragment_RepositoryOwner_User_Fragment;
              };
          })
        | null;
    rateLimit: { __typename: 'RateLimit'; limit: number; remaining: number; used: number; resetAt: unknown } | null;
};

type UserWithReposFragment_RepositoryOwner_Organization_Fragment = ({
    __typename: 'Organization';
    id: string;
    login: string;
} & {
    ' $fragmentRefs'?: {
        UserFragment_RepositoryOwner_Organization_Fragment: UserFragment_RepositoryOwner_Organization_Fragment;
    };
}) & { ' $fragmentName'?: 'UserWithReposFragment_RepositoryOwner_Organization_Fragment' };

type UserWithReposFragment_RepositoryOwner_User_Fragment = ({ __typename: 'User'; id: string; login: string } & {
    ' $fragmentRefs'?: { UserFragment_RepositoryOwner_User_Fragment: UserFragment_RepositoryOwner_User_Fragment };
}) & { ' $fragmentName'?: 'UserWithReposFragment_RepositoryOwner_User_Fragment' };

export type UserWithReposFragment_RepositoryOwnerFragment =
    | UserWithReposFragment_RepositoryOwner_Organization_Fragment
    | UserWithReposFragment_RepositoryOwner_User_Fragment;

export type GetUserRepoBranchesQueryVariables = Exact<{
    userName: string;
}>;

export type GetUserRepoBranchesQuery = {
    repositoryOwner:
        | ({ __typename: 'Organization'; id: string; login: string; avatarUrl: unknown } & {
              ' $fragmentRefs'?: {
                  UserFragment_RepositoryOwner_Organization_Fragment: UserFragment_RepositoryOwner_Organization_Fragment;
              };
          })
        | ({ __typename: 'User'; id: string; login: string; avatarUrl: unknown } & {
              ' $fragmentRefs'?: {
                  UserFragment_RepositoryOwner_User_Fragment: UserFragment_RepositoryOwner_User_Fragment;
              };
          })
        | null;
};

export type GetRepoBranchesQueryVariables = Exact<{
    userName: string;
    repoName: string;
    after?: string | null | undefined;
    count: number;
}>;

export type GetRepoBranchesQuery = {
    repository: {
        __typename: 'Repository';
        id: string;
        branches: {
            __typename: 'RefConnection';
            totalCount: number;
            pageInfo: { __typename: 'PageInfo'; hasNextPage: boolean; endCursor: string | null };
            edges: Array<{
                __typename: 'RefEdge';
                node:
                    | ({ __typename: 'Ref'; id: string; name: string } & {
                          ' $fragmentRefs'?: { BranchInfoRowFragment_RefFragment: BranchInfoRowFragment_RefFragment };
                      })
                    | null;
            } | null> | null;
        } | null;
    } | null;
};

export const CommitWithStatuses_CommitFragmentDoc = {
    kind: 'Document',
    definitions: [
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'CommitWithStatuses_commit' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Commit' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'authoredDate' } },
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'status' },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'commit' },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [{ kind: 'Field', name: { kind: 'Name', value: 'oid' } }],
                                    },
                                },
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'contexts' },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'context' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'state' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'description' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'targetUrl' } },
                                        ],
                                    },
                                },
                                { kind: 'Field', name: { kind: 'Name', value: 'state' } },
                            ],
                        },
                    },
                    { kind: 'Field', name: { kind: 'Name', value: 'commitUrl' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'message' } },
                ],
            },
        },
    ],
} as unknown as DocumentNode<CommitWithStatuses_CommitFragment, unknown>;
export const PullRequestMergeFragment_RefFragmentDoc = {
    kind: 'Document',
    definitions: [
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'PullRequestMergeFragment_ref' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'PullRequest' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'headRefOid' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'number' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'url' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'title' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'mergeStateStatus' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'closed' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'isDraft' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'merged' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'mergeable' } },
                ],
            },
        },
    ],
} as unknown as DocumentNode<PullRequestMergeFragment_RefFragment, unknown>;
export const BranchInfoRowFragment_RefFragmentDoc = {
    kind: 'Document',
    definitions: [
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'BranchInfoRowFragment_ref' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Ref' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'name' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'target' },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                {
                                    kind: 'InlineFragment',
                                    typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Commit' } },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            {
                                                kind: 'FragmentSpread',
                                                name: { kind: 'Name', value: 'CommitWithStatuses_commit' },
                                            },
                                        ],
                                    },
                                },
                            ],
                        },
                    },
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'associatedPullRequests' },
                        arguments: [
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'first' },
                                value: { kind: 'IntValue', value: '1' },
                            },
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'states' },
                                value: { kind: 'ListValue', values: [{ kind: 'EnumValue', value: 'OPEN' }] },
                            },
                        ],
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'edges' },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            {
                                                kind: 'Field',
                                                name: { kind: 'Name', value: 'node' },
                                                selectionSet: {
                                                    kind: 'SelectionSet',
                                                    selections: [
                                                        { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                                        {
                                                            kind: 'FragmentSpread',
                                                            name: {
                                                                kind: 'Name',
                                                                value: 'PullRequestMergeFragment_ref',
                                                            },
                                                        },
                                                    ],
                                                },
                                            },
                                        ],
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'CommitWithStatuses_commit' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Commit' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'authoredDate' } },
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'status' },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'commit' },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [{ kind: 'Field', name: { kind: 'Name', value: 'oid' } }],
                                    },
                                },
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'contexts' },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'context' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'state' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'description' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'targetUrl' } },
                                        ],
                                    },
                                },
                                { kind: 'Field', name: { kind: 'Name', value: 'state' } },
                            ],
                        },
                    },
                    { kind: 'Field', name: { kind: 'Name', value: 'commitUrl' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'message' } },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'PullRequestMergeFragment_ref' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'PullRequest' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'headRefOid' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'number' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'url' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'title' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'mergeStateStatus' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'closed' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'isDraft' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'merged' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'mergeable' } },
                ],
            },
        },
    ],
} as unknown as DocumentNode<BranchInfoRowFragment_RefFragment, unknown>;
export const UserFragment_RepositoryOwnerFragmentDoc = {
    kind: 'Document',
    definitions: [
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'UserFragment_repositoryOwner' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RepositoryOwner' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'User' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'company' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Organization' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                ],
            },
        },
    ],
} as unknown as DocumentNode<UserFragment_RepositoryOwnerFragment, unknown>;
export const UserWithReposFragment_RepositoryOwnerFragmentDoc = {
    kind: 'Document',
    definitions: [
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'UserWithReposFragment_repositoryOwner' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RepositoryOwner' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                    { kind: 'FragmentSpread', name: { kind: 'Name', value: 'UserFragment_repositoryOwner' } },
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'User' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [{ kind: 'Field', name: { kind: 'Name', value: 'id' } }],
                        },
                    },
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Organization' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [{ kind: 'Field', name: { kind: 'Name', value: 'id' } }],
                        },
                    },
                    { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'UserFragment_repositoryOwner' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RepositoryOwner' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'User' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'company' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Organization' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                ],
            },
        },
    ],
} as unknown as DocumentNode<UserWithReposFragment_RepositoryOwnerFragment, unknown>;
export const GetRepositoriesDocument = {
    kind: 'Document',
    definitions: [
        {
            kind: 'OperationDefinition',
            operation: 'query',
            name: { kind: 'Name', value: 'GetRepositories' },
            variableDefinitions: [
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'login' } },
                    type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } } },
                },
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'after' } },
                    type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } },
                },
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'first' } },
                    type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: 'Int' } } },
                },
            ],
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'repositoryOwner' },
                        arguments: [
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'login' },
                                value: { kind: 'Variable', name: { kind: 'Name', value: 'login' } },
                            },
                        ],
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'repositories' },
                                    arguments: [
                                        {
                                            kind: 'Argument',
                                            name: { kind: 'Name', value: 'first' },
                                            value: { kind: 'Variable', name: { kind: 'Name', value: 'first' } },
                                        },
                                        {
                                            kind: 'Argument',
                                            name: { kind: 'Name', value: 'after' },
                                            value: { kind: 'Variable', name: { kind: 'Name', value: 'after' } },
                                        },
                                        {
                                            kind: 'Argument',
                                            name: { kind: 'Name', value: 'orderBy' },
                                            value: {
                                                kind: 'ObjectValue',
                                                fields: [
                                                    {
                                                        kind: 'ObjectField',
                                                        name: { kind: 'Name', value: 'field' },
                                                        value: { kind: 'EnumValue', value: 'NAME' },
                                                    },
                                                    {
                                                        kind: 'ObjectField',
                                                        name: { kind: 'Name', value: 'direction' },
                                                        value: { kind: 'EnumValue', value: 'ASC' },
                                                    },
                                                ],
                                            },
                                        },
                                        {
                                            kind: 'Argument',
                                            name: { kind: 'Name', value: 'ownerAffiliations' },
                                            value: {
                                                kind: 'ListValue',
                                                values: [{ kind: 'EnumValue', value: 'OWNER' }],
                                            },
                                        },
                                    ],
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            { kind: 'Field', name: { kind: 'Name', value: 'totalCount' } },
                                            {
                                                kind: 'Field',
                                                name: { kind: 'Name', value: 'pageInfo' },
                                                selectionSet: {
                                                    kind: 'SelectionSet',
                                                    selections: [
                                                        { kind: 'Field', name: { kind: 'Name', value: 'hasNextPage' } },
                                                        { kind: 'Field', name: { kind: 'Name', value: 'endCursor' } },
                                                    ],
                                                },
                                            },
                                            {
                                                kind: 'Field',
                                                name: { kind: 'Name', value: 'edges' },
                                                selectionSet: {
                                                    kind: 'SelectionSet',
                                                    selections: [
                                                        {
                                                            kind: 'Field',
                                                            name: { kind: 'Name', value: 'node' },
                                                            selectionSet: {
                                                                kind: 'SelectionSet',
                                                                selections: [
                                                                    {
                                                                        kind: 'Field',
                                                                        name: { kind: 'Name', value: 'id' },
                                                                    },
                                                                    {
                                                                        kind: 'Field',
                                                                        name: { kind: 'Name', value: 'name' },
                                                                    },
                                                                    {
                                                                        kind: 'Field',
                                                                        name: { kind: 'Name', value: 'nameWithOwner' },
                                                                    },
                                                                    {
                                                                        kind: 'Field',
                                                                        name: { kind: 'Name', value: 'isFork' },
                                                                    },
                                                                    {
                                                                        kind: 'Field',
                                                                        name: { kind: 'Name', value: 'url' },
                                                                    },
                                                                    {
                                                                        kind: 'Field',
                                                                        name: { kind: 'Name', value: 'description' },
                                                                    },
                                                                    {
                                                                        kind: 'Field',
                                                                        name: { kind: 'Name', value: 'pullRequests' },
                                                                        arguments: [
                                                                            {
                                                                                kind: 'Argument',
                                                                                name: { kind: 'Name', value: 'first' },
                                                                                value: { kind: 'IntValue', value: '1' },
                                                                            },
                                                                            {
                                                                                kind: 'Argument',
                                                                                name: { kind: 'Name', value: 'states' },
                                                                                value: {
                                                                                    kind: 'ListValue',
                                                                                    values: [
                                                                                        {
                                                                                            kind: 'EnumValue',
                                                                                            value: 'OPEN',
                                                                                        },
                                                                                    ],
                                                                                },
                                                                            },
                                                                        ],
                                                                        selectionSet: {
                                                                            kind: 'SelectionSet',
                                                                            selections: [
                                                                                {
                                                                                    kind: 'Field',
                                                                                    name: {
                                                                                        kind: 'Name',
                                                                                        value: 'totalCount',
                                                                                    },
                                                                                },
                                                                            ],
                                                                        },
                                                                    },
                                                                ],
                                                            },
                                                        },
                                                    ],
                                                },
                                            },
                                        ],
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
    ],
} as unknown as DocumentNode<GetRepositoriesQuery, GetRepositoriesQueryVariables>;
export const UserFragmentStoryQueryDocument = {
    kind: 'Document',
    definitions: [
        {
            kind: 'OperationDefinition',
            operation: 'query',
            name: { kind: 'Name', value: 'UserFragmentStoryQuery' },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'repositoryOwner' },
                        arguments: [
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'login' },
                                value: { kind: 'StringValue', value: 'test-id', block: false },
                            },
                        ],
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                {
                                    kind: 'InlineFragment',
                                    typeCondition: {
                                        kind: 'NamedType',
                                        name: { kind: 'Name', value: 'RepositoryOwner' },
                                    },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            {
                                                kind: 'FragmentSpread',
                                                name: { kind: 'Name', value: 'UserFragment_repositoryOwner' },
                                            },
                                        ],
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'UserFragment_repositoryOwner' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RepositoryOwner' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'User' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'company' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Organization' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                ],
            },
        },
    ],
} as unknown as DocumentNode<UserFragmentStoryQueryQuery, UserFragmentStoryQueryQueryVariables>;
export const UseMergePrMutationDocument = {
    kind: 'Document',
    definitions: [
        {
            kind: 'OperationDefinition',
            operation: 'mutation',
            name: { kind: 'Name', value: 'useMergePRMutation' },
            variableDefinitions: [
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'input' } },
                    type: {
                        kind: 'NonNullType',
                        type: { kind: 'NamedType', name: { kind: 'Name', value: 'MergePullRequestInput' } },
                    },
                },
            ],
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'mergePullRequest' },
                        arguments: [
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'input' },
                                value: { kind: 'Variable', name: { kind: 'Name', value: 'input' } },
                            },
                        ],
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'pullRequest' },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            { kind: 'Field', name: { kind: 'Name', value: 'merged' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'state' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'mergeStateStatus' } },
                                        ],
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
    ],
} as unknown as DocumentNode<UseMergePrMutationMutation, UseMergePrMutationMutationVariables>;
export const GetUserWithReposDocument = {
    kind: 'Document',
    definitions: [
        {
            kind: 'OperationDefinition',
            operation: 'query',
            name: { kind: 'Name', value: 'GetUserWithRepos' },
            variableDefinitions: [
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'userName' } },
                    type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } } },
                },
            ],
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'repositoryOwner' },
                        arguments: [
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'login' },
                                value: { kind: 'Variable', name: { kind: 'Name', value: 'userName' } },
                            },
                        ],
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                {
                                    kind: 'InlineFragment',
                                    typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'User' } },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            {
                                                kind: 'FragmentSpread',
                                                name: { kind: 'Name', value: 'UserWithReposFragment_repositoryOwner' },
                                            },
                                        ],
                                    },
                                },
                                {
                                    kind: 'InlineFragment',
                                    typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Organization' } },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            {
                                                kind: 'FragmentSpread',
                                                name: { kind: 'Name', value: 'UserWithReposFragment_repositoryOwner' },
                                            },
                                        ],
                                    },
                                },
                            ],
                        },
                    },
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'rateLimit' },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'limit' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'remaining' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'used' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'resetAt' } },
                            ],
                        },
                    },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'UserFragment_repositoryOwner' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RepositoryOwner' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'User' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'company' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Organization' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'UserWithReposFragment_repositoryOwner' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RepositoryOwner' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                    { kind: 'FragmentSpread', name: { kind: 'Name', value: 'UserFragment_repositoryOwner' } },
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'User' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [{ kind: 'Field', name: { kind: 'Name', value: 'id' } }],
                        },
                    },
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Organization' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [{ kind: 'Field', name: { kind: 'Name', value: 'id' } }],
                        },
                    },
                    { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                ],
            },
        },
    ],
} as unknown as DocumentNode<GetUserWithReposQuery, GetUserWithReposQueryVariables>;
export const GetUserRepoBranchesDocument = {
    kind: 'Document',
    definitions: [
        {
            kind: 'OperationDefinition',
            operation: 'query',
            name: { kind: 'Name', value: 'GetUserRepoBranches' },
            variableDefinitions: [
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'userName' } },
                    type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } } },
                },
            ],
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'repositoryOwner' },
                        arguments: [
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'login' },
                                value: { kind: 'Variable', name: { kind: 'Name', value: 'userName' } },
                            },
                        ],
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                                {
                                    kind: 'FragmentSpread',
                                    name: { kind: 'Name', value: 'UserFragment_repositoryOwner' },
                                },
                            ],
                        },
                    },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'UserFragment_repositoryOwner' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RepositoryOwner' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'User' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'company' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                    {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Organization' } },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'login' } },
                                { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                            ],
                        },
                    },
                ],
            },
        },
    ],
} as unknown as DocumentNode<GetUserRepoBranchesQuery, GetUserRepoBranchesQueryVariables>;
export const GetRepoBranchesDocument = {
    kind: 'Document',
    definitions: [
        {
            kind: 'OperationDefinition',
            operation: 'query',
            name: { kind: 'Name', value: 'GetRepoBranches' },
            variableDefinitions: [
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'userName' } },
                    type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } } },
                },
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'repoName' } },
                    type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } } },
                },
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'after' } },
                    type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } },
                },
                {
                    kind: 'VariableDefinition',
                    variable: { kind: 'Variable', name: { kind: 'Name', value: 'count' } },
                    type: { kind: 'NonNullType', type: { kind: 'NamedType', name: { kind: 'Name', value: 'Int' } } },
                },
            ],
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'repository' },
                        arguments: [
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'name' },
                                value: { kind: 'Variable', name: { kind: 'Name', value: 'repoName' } },
                            },
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'owner' },
                                value: { kind: 'Variable', name: { kind: 'Name', value: 'userName' } },
                            },
                        ],
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                {
                                    kind: 'Field',
                                    alias: { kind: 'Name', value: 'branches' },
                                    name: { kind: 'Name', value: 'refs' },
                                    arguments: [
                                        {
                                            kind: 'Argument',
                                            name: { kind: 'Name', value: 'refPrefix' },
                                            value: { kind: 'StringValue', value: 'refs/heads/', block: false },
                                        },
                                        {
                                            kind: 'Argument',
                                            name: { kind: 'Name', value: 'first' },
                                            value: { kind: 'Variable', name: { kind: 'Name', value: 'count' } },
                                        },
                                        {
                                            kind: 'Argument',
                                            name: { kind: 'Name', value: 'after' },
                                            value: { kind: 'Variable', name: { kind: 'Name', value: 'after' } },
                                        },
                                    ],
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            { kind: 'Field', name: { kind: 'Name', value: 'totalCount' } },
                                            {
                                                kind: 'Field',
                                                name: { kind: 'Name', value: 'pageInfo' },
                                                selectionSet: {
                                                    kind: 'SelectionSet',
                                                    selections: [
                                                        { kind: 'Field', name: { kind: 'Name', value: 'hasNextPage' } },
                                                        { kind: 'Field', name: { kind: 'Name', value: 'endCursor' } },
                                                    ],
                                                },
                                            },
                                            {
                                                kind: 'Field',
                                                name: { kind: 'Name', value: 'edges' },
                                                selectionSet: {
                                                    kind: 'SelectionSet',
                                                    selections: [
                                                        {
                                                            kind: 'Field',
                                                            name: { kind: 'Name', value: 'node' },
                                                            selectionSet: {
                                                                kind: 'SelectionSet',
                                                                selections: [
                                                                    {
                                                                        kind: 'Field',
                                                                        name: { kind: 'Name', value: 'id' },
                                                                    },
                                                                    {
                                                                        kind: 'Field',
                                                                        name: { kind: 'Name', value: 'name' },
                                                                    },
                                                                    {
                                                                        kind: 'FragmentSpread',
                                                                        name: {
                                                                            kind: 'Name',
                                                                            value: 'BranchInfoRowFragment_ref',
                                                                        },
                                                                    },
                                                                ],
                                                            },
                                                        },
                                                    ],
                                                },
                                            },
                                        ],
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'CommitWithStatuses_commit' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Commit' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'authoredDate' } },
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'status' },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'commit' },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [{ kind: 'Field', name: { kind: 'Name', value: 'oid' } }],
                                    },
                                },
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'contexts' },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            { kind: 'Field', name: { kind: 'Name', value: 'avatarUrl' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'context' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'state' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'description' } },
                                            { kind: 'Field', name: { kind: 'Name', value: 'targetUrl' } },
                                        ],
                                    },
                                },
                                { kind: 'Field', name: { kind: 'Name', value: 'state' } },
                            ],
                        },
                    },
                    { kind: 'Field', name: { kind: 'Name', value: 'commitUrl' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'message' } },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'PullRequestMergeFragment_ref' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'PullRequest' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'headRefOid' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'number' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'url' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'title' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'mergeStateStatus' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'closed' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'isDraft' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'merged' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'mergeable' } },
                ],
            },
        },
        {
            kind: 'FragmentDefinition',
            name: { kind: 'Name', value: 'BranchInfoRowFragment_ref' },
            typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Ref' } },
            selectionSet: {
                kind: 'SelectionSet',
                selections: [
                    { kind: 'Field', name: { kind: 'Name', value: 'name' } },
                    { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'target' },
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                {
                                    kind: 'InlineFragment',
                                    typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Commit' } },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            {
                                                kind: 'FragmentSpread',
                                                name: { kind: 'Name', value: 'CommitWithStatuses_commit' },
                                            },
                                        ],
                                    },
                                },
                            ],
                        },
                    },
                    {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'associatedPullRequests' },
                        arguments: [
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'first' },
                                value: { kind: 'IntValue', value: '1' },
                            },
                            {
                                kind: 'Argument',
                                name: { kind: 'Name', value: 'states' },
                                value: { kind: 'ListValue', values: [{ kind: 'EnumValue', value: 'OPEN' }] },
                            },
                        ],
                        selectionSet: {
                            kind: 'SelectionSet',
                            selections: [
                                {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'edges' },
                                    selectionSet: {
                                        kind: 'SelectionSet',
                                        selections: [
                                            {
                                                kind: 'Field',
                                                name: { kind: 'Name', value: 'node' },
                                                selectionSet: {
                                                    kind: 'SelectionSet',
                                                    selections: [
                                                        { kind: 'Field', name: { kind: 'Name', value: 'id' } },
                                                        {
                                                            kind: 'FragmentSpread',
                                                            name: {
                                                                kind: 'Name',
                                                                value: 'PullRequestMergeFragment_ref',
                                                            },
                                                        },
                                                    ],
                                                },
                                            },
                                        ],
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
    ],
} as unknown as DocumentNode<GetRepoBranchesQuery, GetRepoBranchesQueryVariables>;
