name: 'unit tests'
on:
  pull_request:
    branches:
    - main
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "unitTest" ?!
  unitTests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: run tests...
      uses: actions/checkout@v1
      with:
        node-version: '14.x'
    - run: yarn
    - run: yarn test
